### ISSUE TITLE
missing dependency?

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/go-whosonfirst-sqlite-features-index#1] opened 2019-08-21 12:33 UTC
```bash
make tools
go build -mod vendor -o bin/wof-sqlite-index-features cmd/wof-sqlite-index-features/main.go
build command-line-arguments: cannot load github.com/whosonfirst/go-whosonfirst-sqlite-index: open /code/whosonfirst/go-whosonfirst-sqlite-features-index/vendor/github.com/whosonfirst/go-whosonfirst-sqlite-index: no such file or directory
Makefile:6: recipe for target 'tools' failed
make: *** [tools] Error 1
```

manually entering `vendor/github.com/whosonfirst` and cloning the `github.com/whosonfirst/go-whosonfirst-sqlite-index` repo resolved the issue and I was able to build successfully.

How are the dependencies managed? I tried using `dep ensure github.com/whosonfirst/go-whosonfirst-sqlite-index` but it gave the error `could not find project Gopkg.toml, use dep init to initiate a manifest`, so I'm guessing you're not using that to manage the deps?

**Comment by thisisaaronland** [comment] 2020-12-31 18:28
Closing since this probably predates the use of Go modules and I haven't been able to reproduce the problem.

**Closed as completed by thisisaaronland** 2020-12-31 18:28 UTC
